
a = Analysis(['./ranking.py'],
             pathex=['C:/Users/MichaelJohnson/revenewcc'],
             binaries=['C:/Users/MichaelJohnson/Anaconda3/envs/revenew', '.'],
             datas=[
    	        ('./LICENSE', '.'),
             	('./inputdata/*.csv', './inputdata'),
             	('./inputdata/*.xlsx', './inputdata'),
             	('./inputdata/*.pkl', './inputdata'),
             	('./gooey/images/*.png', './gooey/images'),
             	('./gooey/images/*.ico', './gooey/images'),
             	('./gooey/images/*.gif', './gooey/images'),
             	('./gooey/languages/*.json', './gooey/languages'),
             ],
             hiddenimports=['pyodbc'],
             win_no_prefer_redirects=True,
             win_private_assemblies=True,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=False,
          name='ranking',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=False)
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               name='ranking')
